library(ggplot2)
library(GGally)
library(reshape2)
library(clusterProfiler)
library(org.Hs.eg.db)
library(TxDb.Hsapiens.UCSC.hg19.knownGene)

#' Process output file from Activity-By-Contact to add gene information to build Cis-Regulatory Hubs
#' 
#' #'
#' @param ABC.inputFile is a text file generated by Activity-By-Contact score
#' @return an annotated data.frame where gene information was added

process.ABC = function(ABC.inputFile) {
  #Function taking in input the EnhancerPredictions.txt output file from Score-ABC software
  #X chromsome is removed from analysis and gene promoters was added
  
  ABC.input = read.table(ABC.inputFile, header=T)
  
  #Removing of X chromsome due to specific organization of 3D architecture from Dosage Compensation
  ABC.input$chr = as.factor(ABC.input$chr)
  ABC.input.WX = ABC.input[ABC.input$chr != "chrX", ]
  ABC.input.WX$chr = droplevels(ABC.input.WX$chr)
  
  #Distinction between genic enhancers and intergenic enhancers
  ABC.input.WX$typeOf = sub("\\|.*", "", ABC.input.WX$name)
  
  genes = unique(ABC.input.WX$TargetGene)
  
  txdb <- TxDb.Hsapiens.UCSC.hg19.knownGene
  genes.hg19 <- genes(txdb)
  symbol <- AnnotationDbi::select(org.Hs.eg.db,keys = genes.hg19$gene_id, columns = c("SYMBOL"), keytype = "ENTREZID")
  genes.hg19$geneSymbol <- symbol$SYMBOL
  #Retrieve only genes with known promoters
  genesInRRCs = genes.hg19[genes.hg19$geneSymbol%in%genes]
  #gene promoters
  promoters = promoters(genesInRRCs)
  
  df.promoters = data.frame(promoters)
  df.promoters = df.promoters[,c("seqnames", "start", "end", "geneSymbol")]
  colnames(df.promoters) = c("chr", "startProm", "endProm", "TargetGene")
  
  enhancers.promoters = merge(ABC.input.WX, df.promoters, by="TargetGene", all.x=TRUE)
  return(enhancers.promoters)
}

#' Generate summary statistics for ABC-derived data.frame annotated with process.ABC
#' 
#' @param process.ABC a data.frame annotated with process.ABC function
#' @return summary statistics to recapitulate information. 
#' 
summarize.ABC.data.frame = function(process.ABC){
  
  n.pairs = nrow(process.ABC)
  n.unique.enhancers = length(unique(process.ABC$name))
  n.unique.genes = length(unique(process.ABC$TargetGene))
  print(paste0("Number of pairs: ", n.pairs))
  print(paste0("Number of unique enhancers: ", n.unique.enhancers))
  print(paste0("Number of unique genes: ", n.unique.genes))
}

#'
#'
#' @param input
#' @return 
Pairs.from.ABC = function(process.ABC) {
  #Function takes as input the process.ABC output 
  #The function returns a Pairs of GRanges with enhancers and promoters
  GRanges.enhancers = GRanges(seqnames=process.ABC$chr.x, ranges=IRanges(start=process.ABC$start, end=process.ABC$end, names=process.ABC$name), ABC.Score=process.ABC$ABC.Score)
  Granges.promoters = GRanges(seqnames=process.ABC$chr.y, ranges=IRanges(start=process.ABC$startProm, end=process.ABC$endProm, names=process.ABC$TargetGene), ABC.Score=process.ABC$ABC.Score)
  
  return(Pairs(GRanges.enhancers, Granges.promoters))
  
}

#' Function which creates CRHs from the Activity-By-Contact methodology or control methods,
#' Rao (3D-only) and DNAse (3D + DNase) method
#' @param input an annotated data.frame
#' @param method the type of method to build CRHs
#' @return a igraph object with all CRHs
#' 
create.CRHs = function(input, method=c("ABC", "Rao", "DNAse")) { 
  
  if(method =="ABC"){
    #The function creates CRN based on AL1C definition and ABC-Score annotation
    #The function returns a graph from igraph package 
    nodes = input[, c("name", "TargetGene")]
    enhancers = unique(nodes$name)
    vertices =  data.frame(rbind(matrix(unique(nodes$name), ncol=1), matrix(unique(nodes$TargetGene), ncol=1)))
    
    colnames(vertices) = c("name")
    vertices$type = vertices[,"name"]%in%enhancers
    vertices$col = ifelse(vertices[,"name"]%in%enhancers, "blue", "red")
    
    graph = graph_from_data_frame(nodes, directed=F, vertices=vertices)
    return(graph)
  }
  
  else {
    nodes = input[,c("geneSymbol.x","name")]
    nodes = na.omit(nodes)
    vertices = unique(rbind(matrix(nodes$geneSymbol.x, ncol=1), matrix(nodes$name, ncol=1)))
    graph = graph_from_data_frame(nodes, directed = F, vertices=vertices)
    return(graph)
  }
}
#' Function which adds the membership on the original data.frame with pairs of gene-enhancer
#' @param graph a igraph object with CRHs
#' @param df a data.frame with pairs of gene-enhancer
#' @return a data.frame with one additional column with CRH information
#' 
add.membership = function(graph, df){
  membership = components(graph)$membership
  df.membership = data.frame(membership)
  df.membership$name = rownames(df.membership)
  
  df.membership = df.membership[df.membership$name%in%df$name,]
  df = merge(df, df.membership, by="name")
  
  return(df)
  
}

#'This function compares the number of unique genes and enhancers within CRHs 
#' @param df a data.frame with the CRH information
#' @return a list with the paired Wilcoxon rank-sum test and the corresponding aggregated data.frame

compare.genes.enhancers.CRHs = function(df){
  
  unique.genes.per.CRH = aggregate(TargetGene~membership,df, function(x) length(unique(x)))
  unique.enhancers.per.CRH = aggregate(name~membership,df, function(x) length(unique(x)))
  
  colnames(unique.genes.per.CRH)= c("membership", "NGenes")
  colnames(unique.enhancers.per.CRH)= c("membership", "NEnhancers")
  
  unique.elements.per.CRH = merge(unique.genes.per.CRH,unique.enhancers.per.CRH, by="membership")
  
  return(list("Wilcox"=wilcox.test(unique.elements.per.CRH$NGenes, unique.elements.per.CRH$NEnhancers, paired=T), 
       "data"=unique.elements.per.CRH))
  
  
}
#' This function plots CRHs, return only a subset of CRHs if subset parameter is provided 
#' with one or several genes
plot.CRH = function(graph, subset=NULL, df=NULL){
  
  graph.tmp = graph
  #Whether the element is a gene or an enhancer
  V(graph.tmp)$Elements = ifelse(names(V(graph.tmp))%in% df$TargetGene, "Promoters", "Distal")
  
  #Scpefying the color depending on element type
  V(graph.tmp)$color = ifelse(names(V(graph.tmp))%in% df$TargetGene, "#00BFC4","#F8766D")
  V(graph.tmp)$Name = ifelse(names(V(graph.tmp))%in% df$TargetGene , names(V(graph.tmp)), "")
  
  if(is.null(subset)&is.null(df)){
    GGally::ggnet2(graph.tmp, size=4,color="Elements", shape="Elements",palette = "Set1",label="Name",label.size = 6,legend.size = 20,
           legend.position = "none")
    
  }
  
  else if(!is.null(subset)&!is.null(df)){
    decompose = decompose(graph.tmp)
    subset.CRHs = unique(df[df$TargetGene%in%subset, "membership"])
    
    if(length(subset.CRHs)==1){
      print(ggnet2(decompose[[subset.CRHs]], size=4,color="Elements", shape="Elements",palette = "Set1",label="Name",label.size = 6,legend.size = 20,
             legend.position = "none"))
    }
    
    else{
      for(i in 1:length(subset.CRHs)){
        print(ggnet2(decompose[[subset.CRHs[i]]], size=4,color="Elements", shape="Elements",palette = "Set1",label="Name",label.size = 6,legend.size = 20,
               legend.position = "none"))
      }
      
    }
    
  }
  
  
  else if(!is.null(subset)&is.null(df)){
    print("Please provide data.frame to subset CRHs")
  }
  
  
  
  else{
    print("No subset was provided when data.frame has been specified, please verify")
  }
  
}

plot.cdf.connection.patterns = function(graph, enhancers, genes){
  
  data.frame.connect.Regul = data.frame("Connect"=0:max(igraph::degree(graph, v=V(graph)[V(graph)$name%in%enhancers])),"CUMSUM"= cumsum(igraph::degree_distribution(graph, v=V(graph)[V(graph)$name%in%enhancers])),"Type"="Distal")
  data.frame.connect.Prom = data.frame("Connect"=0:max(igraph::degree(graph, v=V(graph)[V(graph)$name%in%genes])),"CUMSUM"= cumsum(igraph::degree_distribution(graph, v=V(graph)[V(graph)$name%in%genes])), "Type"="Promoters")
  
  data.frame.connect.all = rbind(data.frame.connect.Regul,data.frame.connect.Prom)
  
  ggplot(data=data.frame.connect.all,aes(x=Connect, y=CUMSUM, color=Type)) + geom_line(size=1.5) + geom_point(size=3) + ylab("Cumulative Proportion") + xlab("Number of Connections")+theme_light()+
    scale_color_brewer(palette="Set1")+theme(text = element_text(size = 20), legend.position = c(0.6, 0.2), legend.direction = "horizontal") + geom_hline(yintercept=0.80, linetype="dashed",size=1)
  
}


coverage.By.CRH = function(graph, df, method=c("ABC", "Rao", "DNAse")) { 
  
  if(method=="ABC"){
    df$minStart = apply(df[,c("start", "startProm")], 1, min, na.rm=TRUE)
    df$maxEnd = apply(df[,c("end", "endProm")], 1, max,na.rm=TRUE)
  }
  else{
    df$minStart = apply(df[,c("start.x", "start.y")], 1, min,na.rm=TRUE)
    df$maxEnd = apply(df[,c("end.x", "end.y")], 1, max,na.rm=TRUE)
  }
  
  start.cluster = aggregate(minStart~membership, df, min,na.rm=TRUE)
  end.cluster = aggregate(maxEnd~membership, df, max,na.rm=TRUE)
  
  
  df.start.end = unique(merge(merge(start.cluster, end.cluster, by="membership"), df[,c("chr.x", "membership")], by="membership"), all.y=T)
  
  GRanges.cluster = GRanges(seqnames = df.start.end$chr, ranges = IRanges(start=df.start.end$minStart, end=df.start.end$maxEnd, names=df.start.end$compo.graph.membership ) )
  
  return(list("clusters"=GRanges.cluster, "data.frame"=df))
}


plot.CRHs.vs.ABComp = function(CRHs, Compartments){
  
  overlaps.CRHs.Compartments = findOverlaps(CRHs, Compartments)
  
  for(q in unique(queryHits(overlaps.CRHs.Compartments))){
    subj = subjectHits(overlaps.CRHs.Compartments[queryHits(overlaps.CRHs.Compartments) == q])
    mcols(CRHs)[q,"Compartment"] = paste(mcols(Compartments)[subj,"Compartment"][c(1,length(mcols(Compartments)[subj,"Compartment"]))], collapse="")
    
  }
  CRHs$Compartment = ifelse(CRHs$Compartment=="BA","AB", CRHs$Compartment)
  
  df.CRHs.Comp = data.frame(cbind("ABC",matrix(table(CRHs$Compartment), ncol=1), c("AA","AB","BB")))
  
  df.CRHs.Comp$sum_count = length(CRHs)
  
  df.CRHs.Comp$perc = as.numeric(df.CRHs.Comp$X2)/df.CRHs.Comp$sum_count
  
  ggplot(df.CRHs.Comp, aes(x=X3,y=perc*100, fill=X3))+ geom_bar(position="dodge", stat="identity", color="black")+
    ylab("% of CRHs") + xlab("Compartments")+theme_light()+theme(legend.position = "none",text = element_text(size = 20))
  
}

plot.CRHs.vs.TADs = function(CRHs, TADs){
  
  agg.table.TADs.CRHs = melt(table(countOverlaps(CRHs,TADs)))
  
  agg.table.TADs.CRHs$sum_count = length(CRHs)
  
  agg.table.TADs.CRHs$perc = agg.table.TADs.CRHs$value/agg.table.TADs.CRHs$sum_count
  agg.table.TADs.CRHs$group = ifelse(agg.table.TADs.CRHs$Var1>=5, ">=5", agg.table.TADs.CRHs$Var1)
  agg.table.TADs.CRHs = aggregate(perc~group,agg.table.TADs.CRHs, sum)
  agg.table.TADs.CRHs$group = factor(agg.table.TADs.CRHs$group, levels=c("0","1","2","3","4",">=5"))
  
  ggplot(agg.table.TADs.CRHs, aes(x=group, y=perc*100, fill=group)) +
    geom_bar(stat="identity", color="black", position="dodge")+ylab("% of CRHs")+xlab("Number of Overlaps")+theme_light()+theme(legend.position = "none",text = element_text(size = 20))
  
}


Complexity.CRHs = function(graph,enhancers,genes ,extract.central.genes=T) {
  
  compo = components(graph)
  
  
  n.unique.genes = length(unique(genes))
  n.unique.enhancers = length(unique(enhancers))
  
  polygamous.genes = 1-(table(compo$csize)[1][[1]] / n.unique.genes)
  polygamous.enhancers = 1-(table(compo$csize)[1][[1]] / n.unique.enhancers)
  
  prom.enhancer.clusters = tapply(names(compo$membership),compo$membership,function(vec,genes) table(vec%in%genes),genes=genes)
  prom.enhancer.clusters.mat = matrix(unlist(prom.enhancer.clusters),length(unlist(prom.enhancer.clusters))/2,2,byrow = T)
  
  OneN.genes = sum(prom.enhancer.clusters.mat[prom.enhancer.clusters.mat[,1]==1&prom.enhancer.clusters.mat[,2]>1,2])/n.unique.genes
  OneN.enhancers = sum(prom.enhancer.clusters.mat[prom.enhancer.clusters.mat[,2]==1&prom.enhancer.clusters.mat[,1]>1,1])/n.unique.enhancers
  
  if(extract.central.genes){
    
    subgraphs = decompose(graph)
    #If extract.central.genes the function returns the genes connected with several enhancers and the percentage of genes which are central
    #in network
    
    n.central.genes = lapply(subgraphs, function(x) {
      if(sum(names(V(x)) %in% unique(genes))==1 & length(V(x))>2){
        return(1)
      }
    })
    
    
    central.genes = lapply(subgraphs, function(x) {
      if(sum(names(V(x)) %in% unique(enhancers))==1 & length(V(x))>2){
        return(x)
      }
    })
    
    central.genes = list.clean(central.genes,fun = is.null, recursive = F)
    n.central.genes = sum(unlist(n.central.genes))
    
    return(list("polygamous" = list("genes"= polygamous.genes, "enhancers"=polygamous.enhancers), "1N" = list("genes" = OneN.genes, "enhancers" = OneN.enhancers), "Centrality" = list("list.genes" = central.genes , "n.genes"= n.central.genes )))
  }
  
  else {
    return(list("polygamous" = list("genes"= polygamous.genes, "enhancers"=polygamous.enhancers), "1N" = list("genes" = OneN.genes, "enhancers" = OneN.enhancers)))
  }
  
}


plot.complexity = function(graph, complexity.object){
  
  matrix.complexity = data.frame("Percent"=c(complexity.object$polygamous$genes-complexity.object$`1N`$genes, complexity.object$`1N`$genes, complexity.object$polygamous$enhancers-complexity.object$`1N`$enhancers,complexity.object$`1N`$enhancers,1-(complexity.object$polygamous$genes),1-(complexity.object$polygamous$enhancers))*100, "Type" = c(rep("Polygamous Promoters",1), rep("1N Promoters", 1), rep("Polygamous Regulatory", 1), rep("1N Regulatory",1), rep("Monogamous Promoters",1), rep("Monogamous Regulatory",1)))
  matrix.complexity$Kind = ifelse(grepl("Promoters", matrix.complexity$Type), "Promoters","Distal")
  matrix.complexity$Rel = ifelse(grepl("Poly", matrix.complexity$Type), "Polygamous", ifelse(grepl("1N", matrix.complexity$Type), "1N","Monogamous"))
  
  matrix.complexity$Kind = ifelse(matrix.complexity$Kind=="Promoters", "Promoters", "Distal")
  
  ggplot(matrix.complexity, aes(x=Rel,y=Percent, fill=Rel))+geom_bar(position="dodge", stat="identity", color="black")+facet_grid(~Kind)+
    ylab("% of Elements") + xlab("Relationship")+theme_light()+theme(legend.position = "none",axis.text.x=element_text(angle=90, hjust=1),text = element_text(size = 20),axis.text = element_text(size = 20))
  
}


make.Granges.Genes.Enh = function(df){
  
  Granges.enh = unique(GRanges(seqnames = df$chr.x, ranges=IRanges(df$start,df$end, names = df$name)))
  Granges.genes = unique(GRanges(seqnames = df$chr.x, ranges=IRanges(df$startProm,df$endProm, names = df$TargetGene)))
  
  CRHs.elements = do.call("c",GRangesList(Granges.genes, Granges.enh))
  return(CRHs.elements)
}


plot.overlaps.CRHs.chromatin.states = function(GRanges.CRHs.elements, GRanges.chromatin.states){
  
  CRHs.chromatin.meta.states = sapply(split(GRanges.chromatin.states,GRanges.chromatin.states$meta_states),function(x) {
    length(countOverlaps(GRanges.CRHs.elements, x)[countOverlaps(GRanges.CRHs.elements, x)>=1])/length(GRanges.CRHs.elements)}
  )
  
  CRHs.chromatin.states = sapply(split(GRanges.chromatin.states,GRanges.chromatin.states$name),function(x) {
    length(countOverlaps(GRanges.CRHs.elements, x)[countOverlaps(GRanges.CRHs.elements, x)>=1])/length(GRanges.CRHs.elements)}
  )
  
  df.states = data.frame("Name"=names(CRHs.chromatin.states),"Prop"=CRHs.chromatin.states)
  df.meta.states = data.frame("Name"=names(CRHs.chromatin.meta.states),"Prop"=CRHs.chromatin.meta.states)
  df.meta.states$Name = c("Active", "Inactive/Repressor", "Weakly Active")
  
  FigureA = ggplot(df.meta.states,aes(x=reorder(Name,-Prop),y=Prop*100,fill=Name))+geom_bar(position="dodge", stat="identity",color="black")+xlab("Chromatin States")+ylab("% of Elements within CRHs")+theme_light()+theme(legend.position = "none", axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),text = element_text(size = 20),axis.text = element_text(size = 20))
  FigureB = ggplot(df.states,aes(x=reorder(Name,-Prop),y=Prop*100,fill=Name))+geom_bar(position="dodge", stat="identity",color="black")+xlab("Chromatin States")+ylab("% of Elements within CRHs")+theme_light()+theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1),legend.position = "none",text = element_text(size = 20),axis.text = element_text(size = 20))
  
  FigureA.B = ggarrange(FigureA,FigureB, widths=c(2,4),ncol=2, labels=c("A","B"),font.label = list(size = 20, color = "black", face = "bold", family = NULL))
  FigureA.B
  
}


add.Complexity.CRHs = function(df, method=c("ABC", "Rao", "DNAse"), decompose.graph){
  if(method=="ABC"){
    
    
    asso.complexity = aggregate(TargetGene~membership, df, function(x) length(unique(x)))
    asso.complexity$complexity = sapply(seq_along(decompose.graph), function(x) sum(igraph::degree(decompose.graph[[x]])))
    
    length.regul.CRN = aggregate(name~membership, df, function(x) length(unique(x)))
    asso.complexity = merge(asso.complexity, length.regul.CRN)
    
    return(asso.complexity)
  }
  
  else{
    
    
    asso.complexity = aggregate(geneSymbol.x~membership, df, function(x) length(unique(x)))
    asso.complexity$complexity = sapply(seq_along(decompose.graph), function(x) sum(igraph::degree(decompose.graph[[x]])))
    
    length.regul.CRN = aggregate(name~membership, df, function(x) length(unique(x)))
    asso.complexity = merge(asso.complexity, length.regul.CRN)
    
    return(asso.complexity)
  }
}


#Does not work properly: further investigations are needed
proportion.chromatinStates.by.CRH = function(GRange.CRHs, GRange.chromatinState,df, asso.complex.df, method=c("ABC", "DNAse","Rao"), type=c("all","meta")){
  
  tmp.Regul = GRange.CRHs
  tmp.CS = GRange.chromatinState
  tmp.asso = asso.complex.df
  
  overlaps.CS = findOverlaps(tmp.Regul, tmp.CS)
  subset.CS = tmp.CS[queryHits(overlaps.CS)]
  
  if(method=="ABC"){
    tmp.CS$Regul.name[subjectHits(overlaps.CS)] = names(tmp.Regul[queryHits(overlaps.CS)])
  }
  else{
    names(tmp.Regul) = paste0(seqnames(tmp.Regul),":",start(tmp.Regul),":",end(tmp.Regul))
    mcols(tmp.CS)[subjectHits(overlaps.CS),"Regul.name"] = names(tmp.Regul[queryHits(overlaps.CS)])
  }
  
  
  if(type=="all"){
    states = data.frame(tmp.CS[!is.na(tmp.CS$Regul.name)])
    crossed.table = table(states$Regul.name, states$name)
    
    df.crossed.table = data.frame(matrix(crossed.table,ncol=18))
    colnames(df.crossed.table) = colnames(crossed.table)
    df.crossed.table$name = rownames(crossed.table)
    
    
    df.add.CS = merge(df, df.crossed.table, by="name", all.x=T)
    
    l = lapply(colnames(crossed.table), function(x) {
      f = as.formula(paste0("`",x,"`","~", "membership"))
      # f = as.formula(paste0(x,"~", "membership"))
      aggregate(f, df.add.CS, sum)
    }
    )
    df.l = Reduce(function(dtf1, dtf2) merge(dtf1, dtf2, by = "membership", all.x = TRUE),l)
    
    tmp.asso = merge(tmp.asso,df.l, by="membership", all.x=T)
    
    prop.CS = tmp.asso[,-c(1,2,3,4,5)]/rowSums(tmp.asso[,-c(1,2,3,4,5)])
    
    
    max.prop.CS = apply(prop.CS, 1, which.max)
    return(max.prop.CS)
  }
  else{
    states = data.frame(tmp.CS[!is.na(tmp.CS$Regul.name)])
    crossed.table = table(states$Regul.name, states$meta_states)
    
    df.crossed.table = data.frame(matrix(crossed.table,ncol=3))
    colnames(df.crossed.table) = colnames(crossed.table)
    df.crossed.table$name = rownames(crossed.table)
    
    
    df.add.CS = merge(df, df.crossed.table, by="name", all.x=T)
    
    l = lapply(colnames(crossed.table), function(x) {
      #f = as.formula(paste0("`",x,"`","~", "membership"))
      f = as.formula(paste0(x,"~", "membership"))
      aggregate(f, df.add.CS, sum)
    }
    )
    df.l = Reduce(function(dtf1, dtf2) merge(dtf1, dtf2, by = "membership", all.x = TRUE),l)
    
    tmp.asso = merge(tmp.asso,df.l, by="membership", all.x=T)
    
    prop.CS = tmp.asso[,-c(1,2,3,4,5)]/rowSums(tmp.asso[,-c(1,2,3,4,5)])
    return(prop.CS)
  }
  #all.prop.CS = apply(prop.CS, 1, function(x) cumsum(sort(x, decreasing=T)))
  # 
  # eighty.perc.by.RRC = lapply(1:length(all.prop.CS), function(x){
  #   if(any(all.prop.CS[[x]]<=0.8)){
  #     all.prop.CS[[x]][all.prop.CS[[x]]<=0.8]
  #   }
  #   else{
  #     all.prop.CS[[x]][1]
  #   }}
  #   
  #   )
  # 
  # 
  # return(eighty.perc.by.RRC)
  #return(prop.CS)
  
}


plot.CRHs.GO.enrichment = function(df, ID2geneSymbol){
  
  a = lapply(unique(df$membership), function(x){
    
    u = unique(df[df$membership==x,"TargetGene"])
    
    return(ID2geneSymbol[ID2geneSymbol$SYMBOL%in%u,"ENTREZID"])
  })
  
  names(a) = paste0("X", 1:length(a))
  a.bis = Filter(function(x) length(x) >= 10 & length(x) <=50, a)
  
  ck.GO.ABC = clusterProfiler::compareCluster(geneCluster = a.bis, fun = 'enrichGO',OrgDb = org.Hs.eg.db)
  df.ck.GO.ABC = data.frame(ck.GO.ABC)
  order.GO.categories = df.ck.GO.ABC[order(df.ck.GO.ABC$p.adjust), ]
  
  colourCount = length(unique(order.GO.categories[1:20,"Description"]))
  getPalette = colorRampPalette(brewer.pal(9, "Set1"))
  
  plot.GO.genes = ggplot(data=df.ck.GO.ABC[1:20, c("term_name", "p_value")], aes(x=reorder(term_name,-log(p_value)), y=-log(p_value), fill=term_name))+geom_bar(stat="identity", position="dodge",color="black")+coord_flip()+theme(legend.position = "none")+xlab("Biological Processes") + ylab("-log(pvalue)")+theme(axis.text = element_text(size = 8,face="bold"))
  plot.GO.genes
  
}
